name: Build Docs
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build-docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-docs
      - name: Install Flit
        if: steps.cache.outputs.cache-hit != 'true'
        run: python3.7 -m pip install flit
      - name: Install docs extras
        if: steps.cache.outputs.cache-hit != 'true'
        run: python3.7 -m flit install --deps production --extras doc
      - name: Install Material for MkDocs Insiders
        if: github.event.pull_request.head.repo.fork == false && steps.cache.outputs.cache-hit != 'true'
        run: pip install mkdocs-material
      - name: Build Docs
        run: python3.7 ./scripts/docs.py build-lang en
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './site'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
